### ISSUE TITLE
Script stops if there's a backup - Also, backups random naming

### ISSUE THREAD

**Issue by v9999** [J-Bentley/mc-backup.sh#2]
Hello there, thanks for the script, it works perfectly for restarting my server, however, backing up seems to be bugged.

If there's any file in the backup folder, the scripts says this and stops completely:
`[2022-02-24-17:31] Warning: Backup directory not empty! Deleting contents before proceeding...`

I thought it would resume, but it doesn't. 
I'm running Ubuntu on Raspberry Pi 4:
`Linux ubuntu 5.4.0-1052-raspi #58-Ubuntu SMP PREEMPT Mon Feb 7 16:52:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

Also, the backups are named very oddly, with random characters, like: ASDQWE1.tar 
However, the backups generated from "-w" seem to be ok. Just the naming is strange, also the backup file handling.
It would be nice if the script kept a few backups and deleted the older ones to save space.

My config looks like this:
`serverDir=/mnt/exthd/minecraft
backupDir=/mnt/exthd/minecraft_backup
serverName="minecraft2"
startScript="bash start_purpur.sh"
gracePeriod="20s"
serverWorlds=("minecraft2" "minecraft2_nether" "minecraft2_the_end")`

**Comment by Pragalbha-Patil** [comment]
Hi, thanks for the script, pretty useful, however I'm also facing the same issue and my server also doesn't restart after full backup

**Comment by J-Bentley** [comment]
Sorry for abandoning this project, haven't had as much time for pet projects this year. Thanks for such a detailed ticket, the issue with script not continuing with an old backup is fixed and the script no longer deletes old backups. Wondering if you still get randomly named files, that might be fixed now too.
